# Table of Contents
 <p>

In [1]:
#latest version

import numpy as np
import scipy as sp
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D
from matplotlib.ticker import LinearLocator
from matplotlib import cm
import math


def random_three_vector_sphere_1():
    """
    Generates a random 3D unit vector (direction) with a uniform spherical distribution
    Algo from http://stackoverflow.com/questions/5408276/python-uniform-spherical-distribution
    :return:
    """
    phi = np.random.uniform(0,np.pi*2)
    costheta = np.random.uniform(-1,1)

    theta = np.arccos( costheta )
    x = np.sin( theta) * np.cos( phi )
    y = np.sin( theta) * np.sin( phi )
    z = np.cos( theta )
    return (x,y,z)

def random_three_vector_sphere_2(cx = 1 , cy = 1, cz = 1, radius = 1, restrict = False):
    """
    Generates a random 3D unit vector (direction) with a uniform spherical distribution
    Algo from http://mathworld.wolfram.com/SpherePointPicking
    :return:
    """

    if (restrict == True) :
       U = np.random.uniform(0.495,0.505)
       V = np.random.uniform(0.505,0.495)
    else :    
       U = np.random.uniform(0,1)
       V = np.random.uniform(0,1)
    
    theta = np.pi*2*U
    cosphi = 2*V - 1

    phi = np.arccos( cosphi )
    x = np.sin( phi ) * np.cos( theta )
    y = np.sin( phi ) * np.sin( theta )
    z = np.cos( phi )
    return (x*radius+cx,y*radius+cy,z*radius+cz)

def random_next_vertix(px ,py, pz, delta = 0.001):
    cx = 1 
    cy = 1 
    cz = 1 
    r = 1
    max_trial = 10000
    alt_values_tested = 0

    nx, ny, nz = random_three_vector_sphere_2(px, py, pz, delta, True)
    d = math.sqrt((nx-cx)**2 + (ny-cy)**2 + (nz-cz)**2)

    while ((d > r) & (alt_values_tested < max_trial)) :
        #print("distance d: ", d, " is greater than r: ", r)
        tx, ty, tz = random_three_vector_sphere_2(nx, ny, nz, delta, True)
        d = math.sqrt((tx-cx )**2 + (ty-cy)**2 + (tz-cz)**2)   
        alt_values_tested += 1
 
    print("accepted distance d: ", d, " is less than r: ", r)

    if(alt_values_tested > 0) :
        return tx,ty,tz
    
    if(alt_values_tested >= max_trial) :
        print("max trial reached: ", alt_values_tested)
        return 0,0,0
    
    return nx, ny, nz

X = []
Y = []
Z = []

delta = 0.001
n = 10

fig = plt.figure()
ax = fig.add_subplot(111, projection='3d')

#first vertix on unit sphere
x1,y1,z1 = random_three_vector_sphere_2()
print(x1, y1, z1)
X.append(x1)
Y.append(y1)
Z.append(z1)
#ax.scatter(x1, y1, z1)

xs,ys,zs = random_next_vertix(x1,y1,z1,delta)
print(xs, ys, zs)
X.append(xs)
Y.append(ys)
Z.append(zs)
#ax.scatter(xs, ys, zs)

for i in range(n):
    nx,ny,nz = random_next_vertix(xs,ys,zs,delta)
    print(nx, ny, nz)
    if (nx == ny == nz == 0):
        print("FAIL")
        break 
    xs = nx
    ys = ny
    zs = nz
    #ax.scatter(xs, ys, zs)
    X.append(xs)
    Y.append(ys)
    Z.append(zs)
    
#Test 1 - tri-surface plot    
#ax.plot_trisurf(X, Y, Z, cmap=cm.jet, linewidth=0.2)
#ax.set_zlim3d(-1, 1)
#ax.set_ylim3d(-1, 1)
#ax.set_xlim3d(-1, 1)

#Test 2 - wireframe
#ax.plot_wireframe(X, Y, Z)

#Test 3 - scatterplot
#ax.scatter(X, Y, Z)
ax.set_xlabel('X axis')
ax.set_ylabel('Y axis')
ax.set_zlabel('Z axis')
#ax.set_zlim3d(-1, 1)
#ax.set_ylim3d(-1, 1)
#ax.set_xlim3d(-1, 1)

print(X,Y,Z)
#plt.show()

0.78581320194 1.90915957549 1.35714546312
accepted distance d:  1.0004198203477317  is less than r:  1
0.783813290442 1.90915330791 1.35713216919
accepted distance d:  1.0008768738686882  is less than r:  1
0.781813447448 1.90917677983 1.35713684766
accepted distance d:  1.0013467726146135  is less than r:  1
0.779813987716 1.90921117444 1.35713935556
accepted distance d:  1.0018298072755374  is less than r:  1
0.777814602663 1.90925995644 1.3571315494
accepted distance d:  1.0022632583825366  is less than r:  1
0.775815016948 1.90924439793 1.35713772877
accepted distance d:  1.00274424295202  is less than r:  1
0.773815484533 1.909282041 1.3571312807
accepted distance d:  1.0032405853663882  is less than r:  1
0.771816150979 1.90933019612 1.35713078499
accepted distance d:  1.003686935405634  is less than r:  1
0.769816332272 1.90931621793 1.35713717144
accepted distance d:  1.0041691410484919  is less than r:  1
0.767816721088 1.90934047985 1.35713650127
accepted distance d:  1.00466

In [491]:
print(X,Y,Z)

[0.84704595724004594, 0.84504674706363214, 0.84304705998005536, 0.8410473652272441, 0.83904806667147014, 0.83704840570109107, 0.8350489656833826, 0.83304905673387053, 0.83104970141498558, 0.82905013431773478, 0.8270505909123006, 0.8250509478827357] [1.9882032910561267, 1.9882118670585309, 1.9881963099315771, 1.9882151133074282, 1.9881632806190077, 1.988152306522299, 1.9881977440166267, 1.9882155232135084, 1.9882288340816792, 1.9882504531474157, 1.9882705238386404, 1.988306729847545] [1.0077017107986803, 1.0077103105301621, 1.0077218913803383, 1.0077208360055929, 1.0077159032896408, 1.0077132490912459, 1.0077240290770439, 1.0077250597982346, 1.0077299318513646, 1.0077171392517568, 1.0077151726516975, 1.0077218940868267]


In [492]:
pts1 = np.concatenate((X,Y,Z), axis=0)
pts1.shape
pts1 = pts1.reshape(3,12)

In [493]:
pts1.shape

(3, 12)

In [494]:
import numpy as np
from scipy.interpolate import splprep, splev
import matplotlib.pyplot as plt
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D
from matplotlib.ticker import LinearLocator
from matplotlib import cm
import math

fig = plt.figure()
ax = fig.add_subplot(111, projection='3d')

# define pts from the question
#pts = ([-0.51714652353348667, -0.51914626595876479, -0.52114582776268714, -0.52314570587807596, -0.52514567514785293, -0.52714505634877262, -0.52914427678583342, -0.53114385055935354, -0.53314380917900406, -0.53514344800947344, -0.53714265146629292, -0.53914236761475232], [0.69310858227488714, 0.69313746582151103, 0.69309789216573292, 0.6930839288583821, 0.69307941555169583, 0.69312813790583283, 0.69318288928005989, 0.69322371603180488, 0.69321403441562812, 0.69321363625268517, 0.69321584754485255, 0.69321734193783002], [0.50215532096565996, 0.50215093838366898, 0.5021578927784065, 0.50216130912733126, 0.50216909052133873, 0.50216987717867556, 0.50216557332589218, 0.50216482050716404, 0.50215763345547715, 0.50214640126771226, 0.50214018178357689, 0.5021348072775893])
pts = ([0.75065343495819159, 0.7496535802808284, 0.7486536559389646, 0.74765381721132484, 0.74665387066796651, 0.7456541006911076, 0.74465414440069466, 0.74365420534988147, 0.7426546791071672, 0.74165516478326921, 0.74065523618155216, 0.7396557289833009] , [0.5890485756393381, 0.58903243777061298, 0.5890231693312139, 0.5890407658818686, 0.58903317615740747, 0.58901287282017845, 0.58902096978508867, 0.58902831588184101, 0.58899755017935762, 0.58902864206151206, 0.58904053551098545, 0.5890718910042394], [-0.29923434983760627, -0.29923984468500903, -0.29924793211843148, -0.29925152100638247, -0.29925854286570452, -0.29925163143539918, -0.2992469563500656, -0.29925519828681318, -0.29925432554623621, -0.29925222526366008, -0.29925106883477326, -0.29924958772478094])
tck, u = splprep(pts1, u=None, s=0.0) 
u_new = np.linspace(u.min(), u.max(), 300)
x_new, y_new, z_new = splev(u_new, tck, der=0)

import pprint
pprint.pprint((x_new, y_new, z_new))

(array([ 0.84704596,  0.84697238,  0.84689881,  0.84682524,  0.84675167,
        0.84667809,  0.84660452,  0.84653095,  0.84645738,  0.84638381,
        0.84631024,  0.84623668,  0.84616311,  0.84608954,  0.84601597,
        0.84594241,  0.84586884,  0.84579527,  0.84572171,  0.84564814,
        0.84557458,  0.84550101,  0.84542745,  0.84535388,  0.84528032,
        0.84520675,  0.84513319,  0.84505962,  0.84498606,  0.84491249,
        0.84483893,  0.84476537,  0.8446918 ,  0.84461824,  0.84454467,
        0.84447111,  0.84439755,  0.84432398,  0.84425042,  0.84417685,
        0.84410329,  0.84402972,  0.84395616,  0.84388259,  0.84380902,
        0.84373546,  0.84366189,  0.84358833,  0.84351476,  0.84344119,
        0.84336762,  0.84329406,  0.84322049,  0.84314692,  0.84307335,
        0.84299978,  0.84292621,  0.84285264,  0.84277907,  0.84270549,
        0.84263192,  0.84255835,  0.84248478,  0.84241121,  0.84233764,
        0.84226407,  0.8421905 ,  0.84211693,  0.84204336,  0.8

In [495]:
#ax.plot(pts1[0], pts1[1], pts1[2], 'ro')
ax.plot(x_new, y_new, z_new, 'b--')
plt.show()

In [496]:
inputs = np.concatenate((x_new,y_new,z_new), axis=0)

In [497]:
print(inputs)

[ 0.84704596  0.84697238  0.84689881  0.84682524  0.84675167  0.84667809
  0.84660452  0.84653095  0.84645738  0.84638381  0.84631024  0.84623668
  0.84616311  0.84608954  0.84601597  0.84594241  0.84586884  0.84579527
  0.84572171  0.84564814  0.84557458  0.84550101  0.84542745  0.84535388
  0.84528032  0.84520675  0.84513319  0.84505962  0.84498606  0.84491249
  0.84483893  0.84476537  0.8446918   0.84461824  0.84454467  0.84447111
  0.84439755  0.84432398  0.84425042  0.84417685  0.84410329  0.84402972
  0.84395616  0.84388259  0.84380902  0.84373546  0.84366189  0.84358833
  0.84351476  0.84344119  0.84336762  0.84329406  0.84322049  0.84314692
  0.84307335  0.84299978  0.84292621  0.84285264  0.84277907  0.84270549
  0.84263192  0.84255835  0.84248478  0.84241121  0.84233764  0.84226407
  0.8421905   0.84211693  0.84204336  0.84196979  0.84189622  0.84182266
  0.84174909  0.84167553  0.84160196  0.8415284   0.84145484  0.84138128
  0.84130772  0.84123416  0.84116061  0.84108706  0

In [498]:
len(inputs)

900

In [499]:
inputs = inputs.reshape(3,300)

In [500]:
print("input curve means: ", np.mean(inputs, axis=1))
print("input curve sd: ", np.std(inputs, axis=1))

input curve means:  [ 0.8360484   1.98821446  1.00771859]
input curve sd:  [  6.37055269e-03   3.71342956e-05   6.51533145e-06]


In [501]:
inputs.shape

(3, 300)

In [502]:
x = inputs[0]
y = inputs[1]
z = inputs[2]

In [503]:
def add_noise(inputs, mean, std_dev):
    result = map(lambda x: x + np.random.normal(mean,std_dev,x.shape), inputs)
    return result

In [504]:
add_noise(x, 0, 0.01)

[0.83529280814153173,
 0.84599296282238801,
 0.84882359054477186,
 0.84133600250071527,
 0.83503749010296258,
 0.83808053876096078,
 0.84764059681924075,
 0.83209117566920943,
 0.82804161641066587,
 0.85014998006409603,
 0.83709485078164514,
 0.84875656417304501,
 0.84258881899296034,
 0.82572591250043159,
 0.84556619839109159,
 0.85146250227185649,
 0.84632590081587322,
 0.85734562980058326,
 0.86195455019534706,
 0.84730701136539388,
 0.86170833388919843,
 0.84570739005342399,
 0.84476587097493749,
 0.84344745265951071,
 0.84089226569273812,
 0.85425823243510235,
 0.85711092141911027,
 0.85438515569204176,
 0.83178758383323026,
 0.84502169803179006,
 0.83461835762317038,
 0.83669355522718813,
 0.84436270985311757,
 0.84625640971985372,
 0.82671484062265499,
 0.84761715124865877,
 0.85080458023937011,
 0.84554301512589447,
 0.83939899996644574,
 0.85088107881359099,
 0.85436354808128623,
 0.82436917826591127,
 0.84506492576383052,
 0.8353885262636539,
 0.82748053300280022,
 0.84975275

In [505]:
#ax.plot(x, y, z, 'ro')
ax.plot(add_noise(x, 0, 0.01), add_noise(y, 0, 0.01), add_noise(z, 0, 0.01), 'b--')
plt.show()

In [ ]:
''' This is a 2-layer Auto-encoder network
'''
from __future__ import division, print_function, absolute_import

import tensorflow as tf
import numpy as np
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D
from matplotlib.ticker import LinearLocator
from matplotlib import cm


# Parameters
learning_rate = 0.1
training_epochs = 200
batch_size = 100 # 300x 300y 300z
display_step = 10
examples_to_show = 1
total_batch = 10

# Network Parameters
n_hidden_1 = 50 # 1st layer num features
n_hidden_2 = 25 # 1st layer num features
n_input = 900 # (300x 300y 300z points on a curve)

# tf Graph input (only pictures)
X = tf.placeholder("float", [None, n_input])

weights = {
    'encoder_h1': tf.Variable(tf.random_normal([n_input, n_hidden_1])),
    'encoder_h2': tf.Variable(tf.random_normal([n_hidden_1, n_hidden_2])),
    'decoder_h1': tf.Variable(tf.random_normal([n_hidden_2, n_hidden_1])),
    'decoder_h2': tf.Variable(tf.random_normal([n_hidden_1, n_input])),
}
biases = {
    'encoder_b1': tf.Variable(tf.random_normal([n_hidden_1])),
    'encoder_b2': tf.Variable(tf.random_normal([n_hidden_2])),
    'decoder_b1': tf.Variable(tf.random_normal([n_hidden_1])),
    'decoder_b2': tf.Variable(tf.random_normal([n_input])),
}


# Building the encoder
def encoder(x):
    # Encoder Hidden layer with sigmoid activation #1
    layer_1 = tf.nn.sigmoid(tf.add(tf.matmul(x, weights['encoder_h1']),
                                   biases['encoder_b1']))
    # Decoder Hidden layer with sigmoid activation #2
    layer_2 = tf.nn.sigmoid(tf.add(tf.matmul(layer_1, weights['encoder_h2']),
                                   biases['encoder_b2']))
    return layer_2

# Building the decoder
def decoder(x):
    # Encoder Hidden layer with sigmoid activation #1
    layer_1 = tf.nn.sigmoid(tf.add(tf.matmul(x, weights['decoder_h1']),
                                   biases['decoder_b1']))
    # Decoder Hidden layer with sigmoid activation #2
    layer_2 = tf.nn.sigmoid(tf.add(tf.matmul(layer_1, weights['decoder_h2']),
                                   biases['decoder_b2']))
    return layer_2



# Construct model
encoder_op = encoder(X)
decoder_op = decoder(encoder_op)

# Prediction
y_pred = decoder_op
# Targets (Labels) are the input data.
y_true = X

# Define loss and optimizer, minimize the squared error
cost = tf.reduce_mean(tf.pow(y_true - y_pred, 2))
optimizer = tf.train.RMSPropOptimizer(learning_rate).minimize(cost)

# Initializing the variables
init = tf.initialize_all_variables()


# Launch the graph
with tf.Session() as sess:
    sess.run(init)
    
     
    # Training cycle
    for epoch in range(training_epochs):
        # Loop over all batches
        start_idx = 0
        step = (start_idx + n_input/3) * batch_size
            
        for j in range(total_batch):
            batch_all = []
            for i in range(batch_size):
                batch_x = (np.concatenate((add_noise(x, 0, 9e-8),
                                    add_noise(y, 0, 9e-8),
                                    add_noise(z, 0, 9e-8)), 
                                      axis=0))
                batch_all.append(batch_x)
            batch_xs = np.asarray(batch_all)    
            # Run optimization op (backprop) and cost op (to get loss value)
            _, c = sess.run([optimizer, cost], feed_dict={X: batch_xs})
            start_idx += step
            #end_idx = (start_idx + n_input/3) * batch_size
        # Display logs per epoch step
        if epoch % display_step == 0:
            print("Epoch:", '%04d' % (epoch+1),
                  "cost=", "{:.9f}".format(c))

    print("Optimization Finished!")

    # Applying encode and decode over test set
    
    test_input = batch_xs[0].reshape(1, n_input)
    
    input_curve = test_input.reshape(3, n_input/3)
    
    encode_decode = sess.run(
        y_pred, feed_dict={X: test_input})

    fig = plt.figure()
    ax = fig.add_subplot(111, projection='3d')           
    
    #print("input_curve", input_curve)                         
    output_curve = np.reshape(encode_decode[0], (3, n_input/3))
    #print("output_curve", output_curve)           
    
    min = np.amin(input_curve, axis=1)
    max = np.amax(input_curve, axis=1)
    
    # now weed out outliers
    fig = plt.figure()
    ax = fig.add_subplot(111, projection='3d')  
    ax.plot(input_curve[0], input_curve[1], input_curve[2], 'r--')
    ax.plot(output_curve[0], output_curve[1], output_curve[2], 'b--')
    #ax.plot(np.clip(output_curve[0], min[0], max[0]), np.clip(output_curve[1], min[1], max[1]), np.clip(output_curve[2], min[2], max[2]), 'bo')
    plt.show()

Instructions for updating:
Use `tf.global_variables_initializer` instead.


Instructions for updating:
Use `tf.global_variables_initializer` instead.


In [487]:
print("input curve means: ", np.mean(input_curve, axis=1))
print("output curve means: ", np.mean(output_curve, axis=1))
print("diff in means: ", np.mean(input_curve, axis=1) - np.mean(output_curve, axis=1))
print("input curve sd: ", np.std(input_curve, axis=1))
print("output curve sd = ",np.std(output_curve, axis=1))


input curve means:  [ 1.25154831  0.4730925   0.18989487]
output curve means:  [ 0.99999279  0.47241527  0.19254802]
diff in means:  [ 0.25155552  0.00067723 -0.00265316]
input curve sd:  [  3.18551356e-03   2.67888119e-05   8.99763729e-06]
output curve sd =  [  3.17718286e-06   1.39398295e-02   4.67704050e-02]


In [339]:
np.amin(input_curve[1])

0.47305105656109064

In [340]:
np.amin(output_curve[1])

3.9362988e-08

In [475]:
means = np.mean(output_curve, axis=1)
min = np.amin(input_curve, axis=1)
max = np.amax(input_curve, axis=1)

output_clean_x = []
output_clean_y = []
output_clean_z = []
j=0

ix=0
iy=1
iz=2
#(output_curve[ix][i] <= max[ix] and (output_curve[ix][i]) >= min[ix])
for i in range(output_curve.shape[1]):
    if (output_curve[iy][i] > (max[iy]) or output_curve[iy][i] < (min[iy])) :
        j+=1
    elif (output_curve[iz][i] > (max[iz]) or output_curve[iz][i] < (min[iz])):
        j+=1
    else:        
        output_clean_x.append(output_curve[ix][i])
        output_clean_y.append(output_curve[iy][i])
        output_clean_z.append(output_curve[iz][i])
        
print (output_clean_x, output_clean_y, output_clean_z)   
print(j)

[] [] []
300


In [509]:
fig = plt.figure()
ax = fig.add_subplot(111, projection='3d')  
'''

ax.plot(add_noise(x, 9e-7/(0+1), 9e-8),
        add_noise(y, 9e-7/(0+1), 9e-8),
        add_noise(z, 9e-7/(0+1), 9e-8), 'r--')
ax.plot(add_noise(x, 9e-7/(20+1), 9e-8),
        add_noise(y, 9e-7/(20+1), 9e-8),
        add_noise(z, 9e-7/(20+1), 9e-8), 'r--')
        '''
ax.plot(output_curve[0], output_curve[1], output_curve[2], 'bo')
plt.show()

In [459]:
X = inputs.T
X

array([[  3.67594504e-03,  -1.86445993e-03,  -1.81148511e-03],
       [  3.65106149e-03,  -1.85101276e-03,  -1.80004874e-03],
       [  3.62618186e-03,  -1.83761543e-03,  -1.78856642e-03],
       [  3.60130635e-03,  -1.82426713e-03,  -1.77703922e-03],
       [  3.57643522e-03,  -1.81096704e-03,  -1.76546818e-03],
       [  3.55156868e-03,  -1.79771431e-03,  -1.75385436e-03],
       [  3.52670695e-03,  -1.78450814e-03,  -1.74219881e-03],
       [  3.50185028e-03,  -1.77134770e-03,  -1.73050257e-03],
       [  3.47699888e-03,  -1.75823217e-03,  -1.71876671e-03],
       [  3.45215298e-03,  -1.74516071e-03,  -1.70699227e-03],
       [  3.42731281e-03,  -1.73213251e-03,  -1.69518031e-03],
       [  3.40247861e-03,  -1.71914674e-03,  -1.68333187e-03],
       [  3.37765059e-03,  -1.70620258e-03,  -1.67144801e-03],
       [  3.35282898e-03,  -1.69329920e-03,  -1.65952978e-03],
       [  3.32801401e-03,  -1.68043578e-03,  -1.64757823e-03],
       [  3.30320591e-03,  -1.66761150e-03,  -1.6355944

In [460]:
X -= np.mean(X, axis = 0) # zero-center the data (important)
cov = np.dot(X.T, X) / X.shape[0] # get the data covariance matrix

In [461]:
X

array([[  3.67594504e-03,  -1.86445993e-03,  -1.81148511e-03],
       [  3.65106149e-03,  -1.85101276e-03,  -1.80004874e-03],
       [  3.62618186e-03,  -1.83761543e-03,  -1.78856642e-03],
       [  3.60130635e-03,  -1.82426713e-03,  -1.77703922e-03],
       [  3.57643522e-03,  -1.81096704e-03,  -1.76546818e-03],
       [  3.55156868e-03,  -1.79771431e-03,  -1.75385436e-03],
       [  3.52670695e-03,  -1.78450814e-03,  -1.74219881e-03],
       [  3.50185028e-03,  -1.77134770e-03,  -1.73050257e-03],
       [  3.47699888e-03,  -1.75823217e-03,  -1.71876671e-03],
       [  3.45215298e-03,  -1.74516071e-03,  -1.70699227e-03],
       [  3.42731281e-03,  -1.73213251e-03,  -1.69518031e-03],
       [  3.40247861e-03,  -1.71914674e-03,  -1.68333187e-03],
       [  3.37765059e-03,  -1.70620258e-03,  -1.67144801e-03],
       [  3.35282898e-03,  -1.69329920e-03,  -1.65952978e-03],
       [  3.32801401e-03,  -1.68043578e-03,  -1.64757823e-03],
       [  3.30320591e-03,  -1.66761150e-03,  -1.6355944

In [462]:
cov

array([[  4.53292580e-06,  -2.30036194e-06,  -2.23256386e-06],
       [ -2.30036194e-06,   1.16743100e-06,   1.13293094e-06],
       [ -2.23256386e-06,   1.13293094e-06,   1.09963292e-06]])

In [463]:
U,S,V = np.linalg.svd(cov)

In [464]:
Xrot = np.dot(X, U) # decorrelate the data

In [465]:
Xrot_reduced = np.dot(X, U[:,:3])

In [471]:
Xrot_reduced

array([[ -4.50225045e-03,  -1.41864187e-06],
       [ -4.47176331e-03,  -2.57727164e-06],
       [ -4.44128154e-03,  -3.66821358e-06],
       [ -4.41080541e-03,  -4.69279639e-06],
       [ -4.38033520e-03,  -5.65234877e-06],
       [ -4.34987115e-03,  -6.54819940e-06],
       [ -4.31941355e-03,  -7.38167698e-06],
       [ -4.28896266e-03,  -8.15411021e-06],
       [ -4.25851875e-03,  -8.86682778e-06],
       [ -4.22808208e-03,  -9.52115838e-06],
       [ -4.19765292e-03,  -1.01184307e-05],
       [ -4.16723154e-03,  -1.06599735e-05],
       [ -4.13681821e-03,  -1.11471153e-05],
       [ -4.10641319e-03,  -1.15811850e-05],
       [ -4.07601675e-03,  -1.19635111e-05],
       [ -4.04562916e-03,  -1.22954225e-05],
       [ -4.01525069e-03,  -1.25782477e-05],
       [ -3.98488160e-03,  -1.28133156e-05],
       [ -3.95452216e-03,  -1.30019547e-05],
       [ -3.92417263e-03,  -1.31454937e-05],
       [ -3.89383330e-03,  -1.32452615e-05],
       [ -3.86350441e-03,  -1.33025866e-05],
       [ -

In [472]:
fig = plt.figure()
ax = fig.add_subplot(111, projection='3d')  
ax.plot(Xrot_reduced[0], Xrot_reduced[1], 'r--')
plt.show()