# Table of Contents
 <p>

In [2]:
import numpy as np
import scipy as sp
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D
from matplotlib.ticker import LinearLocator
from matplotlib import cm
import math


def random_three_vector_sphere_1():
    """
    Generates a random 3D unit vector (direction) with a uniform spherical distribution
    Algo from http://stackoverflow.com/questions/5408276/python-uniform-spherical-distribution
    :return:
    """
    phi = np.random.uniform(0,np.pi*2)
    costheta = np.random.uniform(-1,1)

    theta = np.arccos( costheta )
    x = np.sin( theta) * np.cos( phi )
    y = np.sin( theta) * np.sin( phi )
    z = np.cos( theta )
    return (x,y,z)

def random_three_vector_sphere_2(cx = 0 , cy = 0, cz = 0, radius = 1, restrict = False):
    """
    Generates a random 3D unit vector (direction) with a uniform spherical distribution
    Algo from http://mathworld.wolfram.com/SpherePointPicking
    :return:
    """

    if (restrict == True) :
       U = np.random.uniform(0.495,0.505)
       V = np.random.uniform(0.505,0.495)
    else :    
       U = np.random.uniform(0,1)
       V = np.random.uniform(0,1)
    
    theta = np.pi*2*U
    cosphi = 2*V - 1

    phi = np.arccos( cosphi )
    x = np.sin( phi ) * np.cos( theta )
    y = np.sin( phi ) * np.sin( theta )
    z = np.cos( phi )
    return (x*radius+cx,y*radius+cy,z*radius+cz)

def random_next_vertix(px ,py, pz, delta = 0.001):
    cx = 0 
    cy = 0 
    cz = 0 
    r = 1
    max_trial = 10000
    alt_values_tested = 0

    nx, ny, nz = random_three_vector_sphere_2(px, py, pz, delta, True)
    d = math.sqrt((nx-cx)**2 + (ny-cy)**2 + (nz-cz)**2)

    while ((d > r) & (alt_values_tested < max_trial)) :
        #print("distance d: ", d, " is greater than r: ", r)
        tx, ty, tz = random_three_vector_sphere_2(px, py, pz, delta, True)
        d = math.sqrt((tx-cx )**2 + (ty-cy)**2 + (tz-cz)**2)   
        alt_values_tested += 1
 
    print("accepted distance d: ", d, " is less than r: ", r, "alt_values_tested: ", alt_values_tested)
    
    if(alt_values_tested >= max_trial) :
        print("max trial reached: ", alt_values_tested)
        return 0,0,0
    
    if(alt_values_tested > 0) :
        return tx,ty,tz
    

    return nx, ny, nz

X = []
Y = []
Z = []

delta = 0.1
n = 50

fig = plt.figure()
ax = fig.add_subplot(111, projection='3d')

#first vertix on unit sphere
x1,y1,z1 = random_three_vector_sphere_2()
print(x1, y1, z1)
X.append(x1)
Y.append(y1)
Z.append(z1)
#ax.scatter(x1, y1, z1)

xs,ys,zs = random_next_vertix(x1,y1,z1,delta)
print(xs, ys, zs)
X.append(xs)
Y.append(ys)
Z.append(zs)
#ax.scatter(xs, ys, zs)

for i in range(n):
    nx,ny,nz = random_next_vertix(xs,ys,zs,delta)
    print(nx, ny, nz)
    if (nx == ny == nz == 0):
        print("FAIL")
        break 
    xs = nx
    ys = ny
    zs = nz
    #ax.scatter(xs, ys, zs)
    X.append(xs)
    Y.append(ys)
    Z.append(zs)
    
#Test 1 - tri-surface plot    
#ax.plot_trisurf(X, Y, Z, cmap=cm.jet, linewidth=0.2)
#ax.set_zlim3d(-1, 1)
#ax.set_ylim3d(-1, 1)
#ax.set_xlim3d(-1, 1)

#Test 2 - wireframe
ax.plot_wireframe(X, Y, Z)

#Test 3 - scatterplot
ax.scatter(X, Y, Z)
#ax.set_xlabel('X axis')
#ax.set_ylabel('Y axis')
#ax.set_zlabel('Z axis')
#ax.set_zlim3d(-1, 1)
#ax.set_ylim3d(-1, 1)
#ax.set_xlim3d(-1, 1)

print(X,Y,Z)

plt.show()

0.64063386974 -0.0615642134047 -0.76537447865
accepted distance d:  0.9389357752585685  is less than r:  1 alt_values_tested:  0
0.540634408707 -0.0618248505714 -0.765174825798
accepted distance d:  0.8857937371054456  is less than r:  1 alt_values_tested:  0
0.440637501907 -0.0616537654096 -0.765942523835
accepted distance d:  0.840844349114096  is less than r:  1 alt_values_tested:  0
0.340666300569 -0.0640501478452 -0.766070016157
accepted distance d:  0.8050465136150632  is less than r:  1 alt_values_tested:  0
0.240710699944 -0.0610842109856 -0.765785196504
accepted distance d:  0.7817056716297097  is less than r:  1 alt_values_tested:  0
0.140723255951 -0.0597319284187 -0.766611256779
accepted distance d:  0.7706648062189694  is less than r:  1 alt_values_tested:  0
0.0407687554993 -0.0627195840796 -0.767025687896
accepted distance d:  0.7711113400416812  is less than r:  1 alt_values_tested:  0
-0.0592275814583 -0.0622516140142 -0.766309029627
accepted distance d:  0.78458385056

In [3]:
import numpy as np
import scipy.linalg
from mpl_toolkits.mplot3d import Axes3D
import matplotlib.pyplot as plt


center = np.array([0.0,0.0,0.0])
# select 2 3-dim points on the circumference of the circle
x1,y1,z1 = random_three_vector_sphere_2()
print("Random First point", x1, y1, z1)
x2,y2,z2 = random_three_vector_sphere_2()
print("Random Second point", x2, y2, z2)


data = np.array([[x1,y1,z1], [x2,y2,z2], [0, 0, 0]])

# regular grid covering the domain of the data
X_mesh,Y_mesh = np.meshgrid(np.arange(-1.0, 1.0, 0.25), np.arange(-1.0, 1.0, 0.25))
XX = X_mesh.flatten()
YY = Y_mesh.flatten()

order = 1    # 1: linear, 2: quadratic
if order == 1:
    # best-fit linear plane
    A = np.c_[data[:,0], data[:,1], np.ones(data.shape[0])]
    print("A: ", A)
    C,_,_,_ = scipy.linalg.lstsq(A, data[:,2])    # coefficients
    print("C:", C)
    
    # evaluate it on grid
    Z_mesh = C[0]*X_mesh + C[1]*Y_mesh + C[2]
    print("Z mesh:", Z_mesh)
    
    # or expressed using matrix/vector product
    #Z = np.dot(np.c_[XX, YY, np.ones(XX.shape)], C).reshape(X.shape)

X = np.asarray(X)
Y = np.asarray(Y)
Z = np.asarray(Z)

print("X: ", X)
print("Y: ", Y)
Z_planar = C[0]*X + C[1]*Y + C[2]
#print("Z_planar: ", Z_planar)
    
    
# plot points and fitted surface
fig = plt.figure()
ax = fig.gca(projection='3d')
#ax.plot_surface(X_mesh, Y_mesh, Z_mesh, rstride=1, cstride=1, alpha=0.2)
#ax.scatter(data[:,0], data[:,1], data[:,2], c='r', s=100)
ax.scatter(X, Y, Z_planar, c='r', s=50)
#ax.plot_wireframe(X, Y, Z)

plt.xlabel('X')
plt.ylabel('Y')
ax.set_zlabel('Z')
#ax.axis('equal')
#ax.axis('tight')



u = np.linspace(0, 2 * np.pi, 100)
v = np.linspace(0, np.pi, 100)
#x = 1 * np.outer(np.cos(u), np.sin(v))
#y = 1 * np.outer(np.sin(u), np.sin(v))
#z = 1 * np.outer(np.ones(np.size(u)), np.cos(v))

x = 1 * np.outer(np.cos(u), np.sin(v))
y = 1 *  np.outer(np.sin(u), np.sin(v))
z = 1 * np.outer(np.ones(np.size(u)), np.cos(v))

print("x, y, z: ", x,y,z)
print("len x, len y, len z: ", len(x), len(y) , len(z))

#for i in range(2):
#    ax.plot_surface(x+random.randint(-5,5), y+random.randint(-5,5), z+random.randint(-5,5),  rstride=4, cstride=4, color='b', linewidth=0, alpha=0.5)

#ax.scatter(x, y, z)
#ax.plot_surface(x, y, z,  rstride=4, cstride=4, color='b', linewidth=0, alpha=0.5)

plt.show()

Random First point -0.403178934718 0.571273759878 0.714907712838
Random Second point 0.795593880759 -0.605751123219 0.00979559179814
A:  [[-0.40317893  0.57127376  1.        ]
 [ 0.79559388 -0.60575112  1.        ]
 [ 0.          0.          1.        ]]
C: [  2.08607973e+00   2.72368735e+00  -4.42376517e-16]
Z mesh: [[ -4.80976708e+00  -4.28824715e+00  -3.76672722e+00  -3.24520728e+00
   -2.72368735e+00  -2.20216742e+00  -1.68064749e+00  -1.15912756e+00]
 [ -4.12884524e+00  -3.60732531e+00  -3.08580538e+00  -2.56428545e+00
   -2.04276551e+00  -1.52124558e+00  -9.99725651e-01  -4.78205720e-01]
 [ -3.44792340e+00  -2.92640347e+00  -2.40488354e+00  -1.88336361e+00
   -1.36184368e+00  -8.40323745e-01  -3.18803813e-01   2.02716118e-01]
 [ -2.76700156e+00  -2.24548163e+00  -1.72396170e+00  -1.20244177e+00
   -6.80921838e-01  -1.59401907e-01   3.62118025e-01   8.83637956e-01]
 [ -2.08607973e+00  -1.56455979e+00  -1.04303986e+00  -5.21519931e-01
   -4.42376517e-16   5.21519931e-01   1.0430398

In [4]:
print(X,Y,Z_planar)

[ 0.64063387  0.54063441  0.4406375   0.3406663   0.2407107   0.14072326
  0.04076876 -0.05922758 -0.15921264 -0.25920245 -0.35919925 -0.45919884
 -0.55917324] [-0.06156421 -0.06182485 -0.06165377 -0.06405015 -0.06108421 -0.05973193
 -0.06271958 -0.06225161 -0.06058019 -0.05917305 -0.0585961  -0.05846861
 -0.05623533] [ 1.16873166  0.95941492  0.75127938  0.53620449  0.33576742  0.13086883
 -0.08578166 -0.29310739 -0.49713175 -0.70188585 -0.90891573 -1.11717561
 -1.31964741]


In [5]:
import numpy as np
from scipy.interpolate import splprep, splev
import matplotlib.pyplot as plt
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D
from matplotlib.ticker import LinearLocator
from matplotlib import cm
import math

fig = plt.figure()
ax = fig.add_subplot(111, projection='3d')

# define pts from the question
pts = ([ 0.72762771,  0.62766368,  0.52771606,  0.42775177,  0.3277821 ,
        0.22778265,  0.12778838,  0.02779382, -0.07217182, -0.17215108,
       -0.27214143, -0.37213945, -0.4721351 , -0.5720983 , -0.67209426], 
      [ 0.63403606,  0.63139695,  0.62829471,  0.62568009,  0.62806788,
        0.62774048,  0.62837311,  0.62785683,  0.62526548,  0.62335267,
        0.62209633,  0.621478  ,  0.62205443,  0.61934436,  0.62022494],
       [-0.99374287, -0.84265888, -0.69167959, -0.54059097, -0.38863191,
       -0.23709572, -0.08540191,  0.0660943 ,  0.21718897,  0.36842125,
        0.51978351,  0.67126737,  0.82295359,  0.97402411,  1.12576321])

tck, u = splprep(pts, u=None, s=0.0) 
u_new = np.linspace(u.min(), u.max(), 1000000)
x_new, y_new, z_new = splev(u_new, tck, der=0)

ax.plot(pts[0], pts[1], pts[2], 'ro')
ax.plot(x_new, y_new, z_new, 'b--')
plt.show()

In [25]:
print("len x, len y, len z: ", len(x), len(y) , len(z))

('len x, len y, len z: ', 100, 100, 100)


In [13]:
np.asarray(X)*C[0]

array([-1.76469703, -1.18816032, -0.61148888, -0.03469317,  0.54203989,
        1.11877731,  1.69543959,  2.84878701,  4.00211988,  5.15567796,
        6.30901848,  7.46260452])

In [28]:
0.1 * X_mesh

array([[-0.1  , -0.075, -0.05 , -0.025,  0.   ,  0.025,  0.05 ,  0.075],
       [-0.1  , -0.075, -0.05 , -0.025,  0.   ,  0.025,  0.05 ,  0.075],
       [-0.1  , -0.075, -0.05 , -0.025,  0.   ,  0.025,  0.05 ,  0.075],
       [-0.1  , -0.075, -0.05 , -0.025,  0.   ,  0.025,  0.05 ,  0.075],
       [-0.1  , -0.075, -0.05 , -0.025,  0.   ,  0.025,  0.05 ,  0.075],
       [-0.1  , -0.075, -0.05 , -0.025,  0.   ,  0.025,  0.05 ,  0.075],
       [-0.1  , -0.075, -0.05 , -0.025,  0.   ,  0.025,  0.05 ,  0.075],
       [-0.1  , -0.075, -0.05 , -0.025,  0.   ,  0.025,  0.05 ,  0.075]])

In [16]:
np.array([[1.0,-0.5,0.8], [-0.5,1.1,0.0], [0.8,0.0,1.0]])

array([[ 1. , -0.5,  0.8],
       [-0.5,  1.1,  0. ],
       [ 0.8,  0. ,  1. ]])

In [8]:
data = np.random.multivariate_normal(mean, cov, 50)
data

array([[-0.2777605 ,  1.32813859, -0.11920881],
       [ 0.55264369, -0.12972625,  0.47477805],
       [-0.79218626,  1.0304091 , -0.04437187],
       [-0.04344556, -0.00489085, -0.15571641],
       [ 0.72884131,  2.03885805,  1.89906601],
       [ 0.80235808, -1.13824719, -0.25435004],
       [ 0.14455516,  0.74738004,  1.0732617 ],
       [ 2.90644728, -1.15299468,  2.12354304],
       [ 0.100343  ,  1.1779903 ,  0.54381225],
       [ 1.6397619 , -0.52669809,  1.13694586],
       [-0.85809618, -1.5109512 , -1.89592592],
       [-1.40131293,  2.16865487,  0.22385262],
       [-0.42917352,  1.45223804,  0.92875523],
       [ 0.15694315,  0.67018504,  0.46909576],
       [-0.22574486, -0.62314192, -0.64885829],
       [ 1.76723373, -2.40733194,  0.66064769],
       [ 0.11961253,  0.28673007,  1.05771228],
       [ 0.36947025,  0.88366987,  1.03087129],
       [ 0.23941228,  0.07211673,  0.08316731],
       [-0.14707797,  0.62601446, -0.46737115],
       [ 0.02542991,  0.26044499,  0.528

In [13]:
data[:,0]

array([ 0.49898123,  0.95149692,  0.        ])

In [12]:
x1,y1,z1 = random_three_vector_sphere_2()
print(x1, y1, z1)
x2,y2,z2 = random_three_vector_sphere_2()
print(x2, y2, z2)
data = np.array([[x1,y1,z1], [x2,y2,z2], [0, 0, 0]])
data

0.498981232067 -0.824184266535 0.267839550553
0.951496923667 0.295688573039 0.0849815981676


array([[ 0.49898123, -0.82418427,  0.26783955],
       [ 0.95149692,  0.29568857,  0.0849816 ],
       [ 0.        ,  0.        ,  0.        ]])

In [5]:
np.meshgrid(np.arange(-3.0, 3.0, 0.5), np.arange(-3.0, 3.0, 0.5))

[array([[-3. , -2.5, -2. , -1.5, -1. , -0.5,  0. ,  0.5,  1. ,  1.5,  2. ,
          2.5],
        [-3. , -2.5, -2. , -1.5, -1. , -0.5,  0. ,  0.5,  1. ,  1.5,  2. ,
          2.5],
        [-3. , -2.5, -2. , -1.5, -1. , -0.5,  0. ,  0.5,  1. ,  1.5,  2. ,
          2.5],
        [-3. , -2.5, -2. , -1.5, -1. , -0.5,  0. ,  0.5,  1. ,  1.5,  2. ,
          2.5],
        [-3. , -2.5, -2. , -1.5, -1. , -0.5,  0. ,  0.5,  1. ,  1.5,  2. ,
          2.5],
        [-3. , -2.5, -2. , -1.5, -1. , -0.5,  0. ,  0.5,  1. ,  1.5,  2. ,
          2.5],
        [-3. , -2.5, -2. , -1.5, -1. , -0.5,  0. ,  0.5,  1. ,  1.5,  2. ,
          2.5],
        [-3. , -2.5, -2. , -1.5, -1. , -0.5,  0. ,  0.5,  1. ,  1.5,  2. ,
          2.5],
        [-3. , -2.5, -2. , -1.5, -1. , -0.5,  0. ,  0.5,  1. ,  1.5,  2. ,
          2.5],
        [-3. , -2.5, -2. , -1.5, -1. , -0.5,  0. ,  0.5,  1. ,  1.5,  2. ,
          2.5],
        [-3. , -2.5, -2. , -1.5, -1. , -0.5,  0. ,  0.5,  1. ,  1.5,  2. ,
          2.5],

In [16]:
#latest version

import numpy as np
import scipy as sp
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D
from matplotlib.ticker import LinearLocator
from matplotlib import cm
import math
from sympy import *


def random_three_vector_sphere_1():
    """
    Generates a random 3D unit vector (direction) with a uniform spherical distribution
    Algo from http://stackoverflow.com/questions/5408276/python-uniform-spherical-distribution
    :return:
    """
    phi = np.random.uniform(0,np.pi*2)
    costheta = np.random.uniform(-1,1)

    theta = np.arccos( costheta )
    x = np.sin( theta) * np.cos( phi )
    y = np.sin( theta) * np.sin( phi )
    z = np.cos( theta )
    return (x,y,z)

def random_three_vector_sphere_2(cx = 0 , cy = 0, cz = 0, radius = 1, restrict = False):
    """
    Generates a random 3D unit vector (direction) with a uniform spherical distribution
    Algo from http://mathworld.wolfram.com/SpherePointPicking
    :return:
    """

    if (restrict == True) :
       U = np.random.uniform(0.495,0.505)
       V = np.random.uniform(0.505,0.495)
    else :    
       U = np.random.uniform(0,1)
       V = np.random.uniform(0,1)
    
    theta = np.pi*2*U
    cosphi = 2*V - 1

    phi = np.arccos( cosphi )
    x = np.sin( phi ) * np.cos( theta )
    y = np.sin( phi ) * np.sin( theta )
    z = np.cos( phi )
    return (round(x*radius+cx,2),round(y*radius+cy,2),round(z*radius+cz,2))

def random_next_vertix(px ,py, pz, delta = 0.001):
    cx = 0 
    cy = 0 
    cz = 0 
    r = 1
    max_trial = 10000
    alt_values_tested = 0

    nx, ny, nz = random_three_vector_sphere_2(px, py, pz, delta, True)
    d = math.sqrt((nx-cx)**2 + (ny-cy)**2 + (nz-cz)**2)

    while ((d > r) & (alt_values_tested < max_trial)) :
        print("distance d: ", d, " is greater than r: ", r)
        tx, ty, tz = random_three_vector_sphere_2(nx, ny, nz, delta, True)
        d = math.sqrt((tx-cx )**2 + (ty-cy)**2 + (tz-cz)**2)   
        alt_values_tested += 1
 
    print("accepted distance d: ", d, " is greater than r: ", r)

    if(alt_values_tested > 0) :
        return tx,ty,tz
    
    if(alt_values_tested >= max_trial) :
        print("max trial reached: ", alt_values_tested)
        return 0,0,0
    
    return nx, ny, nz

X = []
Y = []
Z = []

delta = 0.001
n = 10

fig = plt.figure()
ax = fig.add_subplot(111, projection='3d')

#a random vertix on unit sphere
x1,y1,z1 = random_three_vector_sphere_2(0,0,0,1,False)
print("First random point: ", x1, y1, z1)
x2,y2,z2 = random_three_vector_sphere_2(0,0,0,1,False)
print("Second random point: ", x2, y2, z2)
X.append(x1)
Y.append(y1)
Z.append(z1)
#ax.scatter(x1, y1, z1)

#find a plane passing through this point perpendicular 
#to line from center to this point
from sympy import Point3D
from sympy.geometry.plane import Plane
from sympy.abc import t
p = Plane(Point3D(0,0,0), Point3D(x1,y1,z1), Point3D(x2,y2,z2))
print("plane p:", p)
next_point = p.arbitrary_point(t)
print("next point:", next_point)

for i in range(n):
    angle = np.pi*2*np.random.uniform(0,1)
    print("angle: ", angle)
    xs = round(next_point.x.simplify().evalf(subs={t: angle}),3)
    ys = round(next_point.y.simplify().evalf(subs={t: angle}),3)
    zs = round(next_point.z.simplify().evalf(subs={t: angle}),3)
    X.append((xs))
    Y.append((ys))
    Z.append((zs))
    print("xs, ys, zs: ", xs,ys,zs)
    p = Plane(Point3D(xs,ys,zs) , Point3D(0,0,0), Point3D(x1,y1,z1))
    #print("next plane p:", p)
    next_point = p.arbitrary_point(t)
    #print("next point:", next_point)
    
print(X,Y,Z)
ax.plot_wireframe(X, Y, Z)
ax.set_xlabel('X axis')
ax.set_ylabel('Y axis')
ax.set_zlabel('Z axis')
plt.show()

First random point:  -0.14 -0.66 -0.74
Second random point:  -0.25 -0.44 0.86
plane p: Plane(Point3D(0, 0, 0), (-2233/2500, 1527/5000, -517/5000))
next point: Point3D(4466*sqrt(11272087)*(-1527*sin(t) + 4466*cos(t))*sqrt(1/(13639164*sin(2*t) - 17613427*cos(2*t) + 22811463))/11272087 - 2*sqrt(11272087)*sqrt(1/(13639164*sin(2*t) - 17613427*cos(2*t) + 22811463))*cos(t), -1527*sqrt(11272087)*(-1527*sin(t) + 4466*cos(t))*sqrt(1/(13639164*sin(2*t) - 17613427*cos(2*t) + 22811463))/11272087 - 2*sqrt(11272087)*sqrt(1/(13639164*sin(2*t) - 17613427*cos(2*t) + 22811463))*sin(t), 517*sqrt(11272087)*(-1527*sin(t) + 4466*cos(t))*sqrt(1/(13639164*sin(2*t) - 17613427*cos(2*t) + 22811463))/11272087)
angle:  2.7490049820148705
xs, ys, zs:  -0.073 -0.506 -0.86
angle:  2.8718279564310594
xs, ys, zs:  -0.232 -0.635 0.119
angle:  5.823031593320194
xs, ys, zs:  -0.503 -1.538 -0.215
angle:  0.6358431519597726
xs, ys, zs:  -0.828 -2.484 -0.213
angle:  3.08390795023638
xs, ys, zs:  -1.169 -3.361 0.127
angle:  0.

In [19]:
pts1 = np.concatenate((X,Y,Z), axis=0)
pts1 = pts1.reshape(3,11)
pts = pts1

In [20]:
import numpy as np
from scipy.interpolate import splprep, splev
import matplotlib.pyplot as plt
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D
from matplotlib.ticker import LinearLocator
from matplotlib import cm
import math

fig = plt.figure()
ax = fig.add_subplot(111, projection='3d')

tck, u = splprep(pts, u=None, s=0.0) 
u_new = np.linspace(u.min(), u.max(), 1000)
x_new, y_new, z_new = splev(u_new, tck, der=0)

ax.plot(pts[0], pts[1], pts[2], 'ro')
ax.plot(x_new, y_new, z_new, 'b--')
plt.show()

In [21]:
next_point = p.arbitrary_point(t)

In [36]:
next_point.distance(p.p1).simplify()

1

In [32]:
p.equation()

99843037715140391598931339459*x/6250000000000000000000000000 - 677597537975280034353716860257*y/10000000000000000000000000000 + 4889941994502547774340253615549*z/100000000000000000000000000000

In [61]:
N(next_point.x.simplify())

-3.52630547196557e-31*(3.60818114878678e+60*sin(t) + 2.32751250188719e+61*cos(t))*(1/(1.08245434463603e+61*sin(2*t) + 2.16809362544441e+61*cos(2*t) + 4.81444388021715e+61))**0.5

In [63]:
next_point.x.simplify().evalf()

-3.52630547196557e-31*(3.60818114878678e+60*sin(t) + 2.32751250188719e+61*cos(t))*(1/(1.08245434463603e+61*sin(2*t) + 2.16809362544441e+61*cos(2*t) + 4.81444388021715e+61))**0.5

In [65]:
next_point.x.simplify().evalf(subs={t: 0.4})

-0.955865830162551

In [66]:
next_point.y.simplify().evalf(subs={t: 0.4})

-0.282809931689546

In [67]:
next_point.z.simplify().evalf(subs={t: 0.4})

-0.0796181968234168

In [71]:
x=0.8
next_point.z.simplify().evalf(subs={t: x})

-0.282051687712451

In [72]:
next_point.evalf(subs={t: 2})

Point3D(0.444824004817469, -0.452781017948920, -0.772736018652740)

In [34]:
p.random_point(0)

Point3D(-sqrt(72377344894743520142687312801973982845536429408336057250822637)*cos(3802937935871711/4503599627370496)/sqrt(21680936254444124240308163333045557590960876765812061332479282*cos(3802937935871711/2251799813685248) + 10824543446360345313512469872324652490011922399353109276954080*sin(3802937935871711/2251799813685248) + 48144438802171537555207575333017549122621702703541111972697019) - 3194977206884492531165802862688*sqrt(72377344894743520142687312801973982845536429408336057250822637)*(-798744301721123132791450715672*cos(3802937935871711/4503599627370496) + 3387987689876400171768584301285*sin(3802937935871711/4503599627370496))/(72377344894743520142687312801973982845536429408336057250822637*sqrt(21680936254444124240308163333045557590960876765812061332479282*cos(3802937935871711/2251799813685248) + 10824543446360345313512469872324652490011922399353109276954080*sin(3802937935871711/2251799813685248) + 48144438802171537555207575333017549122621702703541111972697019)), -sqrt(72377344

In [5]:
pp = p.perpendicular_plane(Point3D(0,0,0), Point3D(x1,y1,z1))

In [6]:
ap = pp.arbitrary_point()

In [7]:
ap.y

-227147429009476196375026640769*sqrt(926526798343210818604407893458)*sqrt(-1/(699379369333734622229381252689*sin(_t)**2 - 926526798343210818604407893458))*sin(_t)/926526798343210818604407893458